### ISSUE TITLE
Either optimize F# tools or extend command time out to allow slower plugins.

### ISSUE THREAD

**Issue by Greve2001** [MikaelFangel/nixvim-config#29]
Formatting using Fantomas, is too slow on my PC when running on 2.3GHz. However when boosting to 4.6GHz i can run the formatter.

We either need optimize the F# tools or extend command time limit to accomodate slow formatting.

It would be nice to be able to format when being on powersave mode at 900MHz, therefore the time limit should be extend by a factor of 3 - 5, maybe.

**Comment by MikaelFangel** [comment]
#78 should also make it easier to see what the status of the LSP is.
